# fly.toml app configuration file generated for spid-saml-check on 2025-03-22T09:12:37Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'spid-saml-check'
primary_region = 'sjc'

[build]

[http_service]
  internal_port = 8443
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
